### ISSUE TITLE
Probleem met het mergen van 2 datasets

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/mica-beeldherkenning#1]
@EmmaCartuyvels1 kan je wat meer context geven bij dit probleem ?

**Comment by EmmaCartuyvels1** [comment]
Dit probleem is opgelost, ik open een issue voor het volgende

**Comment by EmmaCartuyvels1** [comment]
Data mergen met volgende aanpassingen in preprocessing.py:
`#Join annotations and pickup-setup data
ann = assets.set_index('sequence').join(observations_unique.set_index('sequenceID'))
ann.index.name = 'sequenceId'
data = ann.merge(setup, on='sequenceId', how='left')
data.reset_index(level=0, inplace=True)
data.rename(columns={'index': 'sequenceID'}, inplace=True)
data = data.drop([ 'id','type','originalFilename','destination','directory','exiftoolData','order',
                  'createdAt','isFavourite','observations','isTimeLapse','deployment'], axis=1)
        
data`

Maar creëert erg veel NaN wat niet de bedoeling kan zijn

**Comment by EmmaCartuyvels1** [comment]
![image](https://user-images.githubusercontent.com/44839819/87008256-c4a2ab80-c1c3-11ea-8c74-564e2868518b.png)

**Comment by SanderDevisscher** [comment]
> Data mergen met volgende aanpassingen in preprocessing.py:
> `#Join annotations and pickup-setup data
> ann = assets.set_index('sequence').join(observations_unique.set_index('sequenceID'))
> ann.index.name = 'sequenceId'
> data = ann.merge(setup, on='sequenceId', how='left')
> data.reset_index(level=0, inplace=True)
> data.rename(columns={'index': 'sequenceID'}, inplace=True)
> data = data.drop([ 'id','type','originalFilename','destination','directory','exiftoolData','order',
> 'createdAt','isFavourite','observations','isTimeLapse','deployment'], axis=1)
> 
> data`
> 
> Maar creëert erg veel NaN wat niet de bedoeling kan zijn

dus als ik het goed begrijp zijn deze aanpassingen nog niet "aanwezig" in de master versie van het script ?

**Comment by EmmaCartuyvels1** [comment]
Jawel, dit is al aangepast in preprocessing.py

**Comment by SanderDevisscher** [comment]
ok ik heb pycharm al gedownload, zal strx na de vergadering me er eens opgooien ;-)

**Comment by SanderDevisscher** [comment]
Ik ga deze issue onder de loupe nemen in de `1_get_stuff_working` - branch

**Comment by SanderDevisscher** [comment]
de dataframe data wordt ergens in deze regels leeggemaakt 

https://github.com/inbo/mica-beeldherkenning/blob/12851f48906723ec0f5a0061050eb869172967d3/src/preprocessing/preprocessing.py#L73-L84

Hierdoor kan het script geen verdere bewerkingen doen

**Comment by EmmaCartuyvels1** [comment]
Ik zie het probleem al, in de dataset staan deze als true/false niet WAAR of ONWAAR, probeer eens te veranderen naar true (kleine letters)?

**Comment by EmmaCartuyvels1** [comment]
Hoe ziet de dataset eruit voor regel 83?
Want dropna verwijderd elke regel met na

**Comment by SanderDevisscher** [comment]
> Ik zie het probleem al, in de dataset staan deze als true/false niet WAAR of ONWAAR, probeer eens te veranderen naar true (kleine letters)?

zal na overleg eens proberen

**Comment by SanderDevisscher** [comment]
> Hoe ziet de dataset eruit voor regel 83?
> Want dropna verwijderd elke regel met na

gelijk in het begin

**Comment by EmmaCartuyvels1** [comment]
Hebt ge die aanpassing van mij al gedaan?

**Comment by SanderDevisscher** [comment]
> Hebt ge die aanpassing van mij al gedaan?

Neen, de dataframe data wordt pas in regels 83 en 84 leeg gemaakt denk ik

**Comment by EmmaCartuyvels1** [comment]
Ja maar mijn aanpassing voorkomt veel na's

**Comment by SanderDevisscher** [comment]
Beide kolommen "isBlank" en "isSetupPickup" zijn zover ik kan zien leeg !! => alle regels worden ingevuld als nan en vervolgens verwijderd

**Comment by SanderDevisscher** [comment]
@EmmaCartuyvels1 @damianooldoni ik heb de indruk dat er iets fundamenteel misloopt met de iterrows.  In deze commit https://github.com/inbo/mica-beeldherkenning/commit/613a6f3982ded53671298ba207f283580e1aac18 heb ik de iterrows van de deployments heschreven met de np.where() - methode en gelijk wordt de 'deployment' wel ingevuld. 

**MAAR** in de onderstaande regel wordt een subset gemaakt o.b.v. de deployment: 
https://github.com/inbo/mica-beeldherkenning/blob/613a6f3982ded53671298ba207f283580e1aac18/src/preprocessing/preprocessing.py#L197-L206
Als ik deze regels laat lopen wordt data gesubset o.b.v. de folder waarin de foto's staan en de deployment_ID_ in de data. 
Dit resulteert echter in een lege dataframe omdat de map niet de juiste naam (of datatype => nog te onderzoeken) van de deployment draagt.

**Comment by SanderDevisscher** [comment]
Ik krijg nu deze error: 
Traceback (most recent call last):
```
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/blauw/Documents/GitHub/mica-beeldherkenning/src/preprocessing/preprocessing.py", line 476, in <module>
    preprocessing(general_folder_path, resized_folder_path, preprocessing_output_path)
  File "C:/Users/blauw/Documents/GitHub/mica-beeldherkenning/src/preprocessing/preprocessing.py", **line 234, in preprocessing**
    if os.path.isfile(os.path.join(resized_folder_path,folder,img)):
  File "C:\Users\blauw\anaconda3\envs\mica-beeldherkenning\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\blauw\anaconda3\envs\mica-beeldherkenning\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NAType'
```

deze error wijst op een probleem in deze regels:
https://github.com/inbo/mica-beeldherkenning/blob/06ff9d21fbceb7d50ae71e2fa17d84b757ccabe4/src/preprocessing/preprocessing.py#L233-L237

**Comment by EmmaCartuyvels1** [comment]
Dat is dat die ImagesNames niet het juiste type heeft, zou str moeten zijn

**Comment by SanderDevisscher** [comment]
Ik denk dat er iets misloopt in deze regels:
https://github.com/inbo/mica-beeldherkenning/blob/06ff9d21fbceb7d50ae71e2fa17d84b757ccabe4/src/preprocessing/preprocessing.py#L218-L220
ImagesNames wordt namelijk gevuld met NA - waardes.

**Comment by SanderDevisscher** [comment]
voor het eerst geen foutmelding meer in het preprocessing script B-)
```
Traceback (most recent call last):
  File "C:\Users\blauw\anaconda3\envs\mica-beeldherkenning\lib\site-packages\pandas\core\generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\blauw\anaconda3\envs\mica-beeldherkenning\lib\site-packages\pandas\core\generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "C:\Users\blauw\anaconda3\envs\mica-beeldherkenning\lib\site-packages\pandas\core\internals\managers.py", line 177, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 2 elements
```

alleen weet ik niet hoe ik hier nu verder mee moet

**Comment by SanderDevisscher** [comment]
ik krijg de error ook als ik deze for loop manueel laat lopen:
https://github.com/inbo/mica-beeldherkenning/blob/06ff9d21fbceb7d50ae71e2fa17d84b757ccabe4/src/preprocessing/preprocessing.py#L229-L459

**Comment by EmmaCartuyvels1** [comment]
Maar waar zit deze fout dan juist?

**Comment by SanderDevisscher** [comment]
> Maar waar zit deze fout dan juist?

hier ? 
https://github.com/inbo/mica-beeldherkenning/blob/06ff9d21fbceb7d50ae71e2fa17d84b757ccabe4/src/preprocessing/preprocessing.py#L233-L238

Ik heb een vermoeden dat de gevraagde image niet bestaat in de resized map en dat er omdat er geen else gedefinieerd is geen regel aangemaakt wordt in _images_sequence_

**Comment by EmmaCartuyvels1** [comment]
Ik heb enkel de eerste 1000 beelden binnengehaald om te voorkomen dat het heel lang zou lopen altijd

**Comment by SanderDevisscher** [comment]
de eerste file die geïtereerd wordt is RCNX0054.JPG maar die staat niet in de map

**Comment by SanderDevisscher** [comment]
en we zijn uit de for loop
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/blauw/Documents/GitHub/mica-beeldherkenning/src/preprocessing/preprocessing.py", line 497, in <module>
    preprocessing(general_folder_path, resized_folder_path, preprocessing_output_path)
  File "C:/Users/blauw/Documents/GitHub/mica-beeldherkenning/src/preprocessing/preprocessing.py", **line 484, in preprocessing**
    for i, row in boxes_output.iterrows():
AttributeError: 'NoneType' object has no attribute 'iterrows'
```
nu alleen nog deze iterrows herschrijven:

https://github.com/inbo/mica-beeldherkenning/blob/21807dc95fb125d521b8ce8233b2f99edeeb830f/src/preprocessing/preprocessing.py#L482-L488

**Comment by SanderDevisscher** [comment]
in de dataset die we gebruiken voor de testen is deze if nooit True! 
https://github.com/inbo/mica-beeldherkenning/blob/21807dc95fb125d521b8ce8233b2f99edeeb830f/src/preprocessing/preprocessing.py#L288

hierdoor blijven de dataframes die we verder nodig hebben leeg

**Comment by EmmaCartuyvels1** [comment]
> in de dataset die we gebruiken voor de testen is deze if nooit True!
> https://github.com/inbo/mica-beeldherkenning/blob/21807dc95fb125d521b8ce8233b2f99edeeb830f/src/preprocessing/preprocessing.py#L288
> 
> hierdoor blijven de dataframes die we verder nodig hebben leeg

En van wat zijn dat de rijen?

**Comment by SanderDevisscher** [comment]
for i, row in enumerate(deployment.itertuples(), 1)

**Comment by SanderDevisscher** [comment]
@EmmaCartuyvels1 ik heb het script kunnen doorlopen zonder fout melding. De 4 csvs die gemaakt moeten worden zijn gemaakt en gevuld.

**Comment by EmmaCartuyvels1** [comment]
Super!

Voor de volgende stappen:
1.  run resize_images.py (gelukt zonder problemen
2.  run preprocessing.py (hier zijn we nu)
3.  first run resnet50_bottleneck_features.py (map network)
4.  run resnet50_hierarchical_bottleneck (map network)
5. run resnet50_hierarchical_finetune (top weights nog te bepalen, ik zal dit aan Laura vragen)

Evaluate: hierachical_output_processing_training.py

**Comment by SanderDevisscher** [comment]
up next, get resnet50_bottleneck_features.py running in pycharm

**Comment by damianooldoni** [comment]
Sterk werk, @SanderDevisscher :muscle: Ik zou deze issue afsluiten (zie documentatie stapelplan in #3)

**Comment by SanderDevisscher** [comment]
ok
